language: java

service:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS messageBoard;'  
  - mysql -u root --default-character-set=utf8 messageBoard < db/db.sql

script:
- mvn cobertura:cobertura
- mvn test

after_success:
- bash <(curl -s https://codecov.io/bash)


 